spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lsk123456
    url: jdbc:mysql://localhost:3306/freechat
  redis:
    database: 2
    password: lsk123456
    host: localhost
    port: 6379