spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:
    url: jdbc:mysql://localhost:3306/freechat
  redis:
    database: 2
    password:
    host: localhost
    port: 6379